config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#home'

  resources :workout_components, :workouts, :templates

  get 'schedule_workouts' => 'workouts#schedule_workouts', as: :schedule_workouts
  post 'save_schedule' => 'workouts#save_schedule', as: :save_schedule

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :component_sets, :dependent => :destroy
  has_many :component_times, :dependent => :destroy
  belongs_to :user
  validates :user_id, presence: :true
  accepts_nested_attributes_for :component_sets, :allow_destroy => true, reject_if: proc {|attributes| attributes['workout_component_id'].blank? || attributes['kg'].blank? && attributes['reps'].blank? && attributes['num_of_sets'].blank?}
  accepts_nested_attributes_for :component_times, :allow_destroy => true, reject_if: proc {|attributes| attributes['workout_component_id'].blank? || attributes['meters'].blank?	&& attributes['seconds'].blank?}

  default_scope {order(workout_date: :desc)}
  scope :recent_scheduled, -> {where(completed: false).where('workout_date < ?', Date.today).limit(5)}

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  before_action :authenticate_user!

  def index
    @workouts = current_user.workouts.all
    @templates = current_user.templates.all
  end

  def new
    @templates = current_user.templates.all
  	generate_component_arrays 
    @workout = Workout.new(params[:workout])
    if params[:template]
      load_template(current_user.templates.find(params[:template]), true)
    else
      set_template_to_default
    end
    @workout.workout_date = params[:date] if params[:date]
  end

  def create
    this_workout = Workout.create(workout_params)
    redirect_to workout_url(this_workout)
  end

  def edit
    @workout = current_user.workouts.find(params[:id])
    @templates = current_user.templates.all
    generate_component_arrays
    if @workout.component_sets.count == 0
      @workout.component_sets.new(order: -1)
    end
    if @workout.component_times.count == 0
      @workout.component_times.new(order: -1)
    end
  end

  def update
    @workout = current_user.workouts.find(params[:id])
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end

  def show
    @this_workout = current_user.workouts.find(params[:id])
    @templates = current_user.templates.all
  end

  def destroy
    @workout = current_user.workouts.find(params[:id])
  	@workout.destroy
    respond_to do |format|
      format.js { render :layout => false }
      format.html {redirect_to root_path}
    end
  end

  def schedule_workouts
    @templates = current_user.templates.all
    @workouts = current_user.workouts.all
  end

  def save_schedule
    unless params[:scheduled].nil?
      new_workouts_array = params[:scheduled]
      new_workouts_array.each do |workout|
        date = workout[1][:start]
        @workout = Workout.new(workout_date: date,
                               completed: false,
                               user_id: current_user.id)
        load_template(current_user.templates.find(workout[1][:template_id].to_i), false)
        @workout.save
      end
    end

    response = {response: 'success'}

    respond_to do |format|
      format.json {render json: response.to_json}
    end
  end

  private

  def workout_params
    params.require(:workout).permit(:name, :workout_date, :workout_time, :completed, :notes, 
      component_sets_attributes: [:id, :kg, :reps, :num_of_sets, :workout_component_id, :rest, :_destroy], 
      component_times_attributes: [:id, :meters, :seconds, :workout_component_id, :rest, :_destroy]).merge(user_id: current_user.id)
  end


  def generate_component_arrays
    #initialize arrays to help form the exercise select boxes
    @time_component_array = Array.new
    time_components = WorkoutComponent.where(component_type: "Time").where(equipment: 'Machine')
    @time_component_array.push(['**Cardio Equipment**',''])
    time_components.each do |time_component|
      @time_component_array.push([time_component.name, time_component.id])
    end
    time_components = WorkoutComponent.where(component_type: "Time").where(equipment: 'Road/Track')
    @time_component_array.push(['',''])
    @time_component_array.push(['**Road/Track**',''])
    time_components.each do |time_component|
      @time_component_array.push([time_component.name, time_component.id])
    end
    @set_component_array = Array.new
    set_components = WorkoutComponent.where(component_type: "Reps").where(equipment: 'Machine')
    @set_component_array.push(['**Gym Machines**',''])
    set_components.each do |set_component|
      @set_component_array.push([set_component.name, set_component.id])
    end
        set_components = WorkoutComponent.where(component_type: "Reps").where(equipment: 'Free Weights')
    @set_component_array.push(['',''])
    @set_component_array.push(['**Free Weights**',''])
    set_components.each do |set_component|
      @set_component_array.push([set_component.name, set_component.id])
    end
        set_components = WorkoutComponent.where(component_type: "Reps").where(equipment: 'Body Weight Only')
    @set_component_array.push(['',''])
    @set_component_array.push(['**Body Weight Only**',''])
    set_components.each do |set_component|
      @set_component_array.push([set_component.name, set_component.id])
    end
  end

  def set_template_to_default
    #add some common workouts to get user started when opening blank 
    running = WorkoutComponent.where(name: 'Treadmill').first
    crunches = WorkoutComponent.where(name: 'Crunches').first
    pressups = WorkoutComponent.where(name: 'Press-ups').first
    @workout.component_times.new(workout_component_id: running.id)
    @workout.component_sets.new(workout_component_id: crunches.id)
    @workout.component_sets.new(workout_component_id: pressups.id)
  end

  def load_template(template, add_hidden_fields_to_copy)
    @workout.name = template.name
    @workout.notes = template.notes
    template.component_times.each do |exercise|
      @workout.component_times.new(exercise.attributes.except('id','created_at','updated_at','template_id'))
    end
    template.component_sets.each do |exercise|
      @workout.component_sets.new(exercise.attributes.except('id','created_at','updated_at','template_id'))
    end
    if add_hidden_fields_to_copy
      if template.component_sets.count == 0
        @workout.component_sets.new(order: -1)
      end
      if template.component_times.count == 0
        @workout.component_times.new(order: -1)
      end
    end
  end
end

app/views/workouts/destroy.js.erb
$('#<%= dom_id(@workout) %>').fadeOut();

app/views/workouts/edit.html.erb
<h3>Update Workout</h3>

<br>

    <%= form_for(@workout) do |f| %>

      <%= f.label "Name", class: 'sr-only' %>
      <%= f.text_field :name, placeholder: 'Name - e.g. Cardio' %> - 

      <%= f.label "Date", class: 'sr-only' %>
      <%= f.date_select :workout_date %>
      <%= f.select(:workout_time, ["","morning","afternoon","evening","night"]) %>

      <%= f.radio_button :completed, :true %>
      <%= f.label :completed_true, "Completed" %>
      <%= f.radio_button :completed, :false %>
      <%= f.label :completed_false, "Scheduled" %>
      <br>
      <br>
      <%= render 'layouts/workout_form2', f: f %>

      <%= f.submit "Update Workout"%>

    <% end %>

app/views/workouts/index.html.erb
<h3>All Workouts</h3>
<br>

<table class="table">


<% @workouts.each do |workout| %>
  <tbody class="workout" id="workout_<%= workout.id %>" %>
  	<td><%= workout.workout_date %></td>   	
    <td>
      <% if workout.name.empty? %>
      	<%= link_to "Workout", workout_url(workout.id) %>
      <% else %>
      	<%= link_to workout.name, workout_url(workout.id) %>
      <% end %>
    </td>
    <td>
      <% if workout.completed == true %>
        Completed
      <% else %>
        Scheduled
      <% end %>
    </td>
    <td><%= link_to "view", workout_url(workout.id) %></td>
    <td><%= link_to "update", edit_workout_path(workout.id) %></td>
    <td><%= link_to "delete", workout, method: :delete, remote: true %></td>
  </tbody>
<% end %>

</table>

app/views/workouts/new.html.erb
<h3>Add Workout</h3>

<br>

    <%= form_for(@workout) do |f| %>

      <%= f.label "Name", class: 'sr-only' %>
      <%= f.text_field :name, placeholder: 'Name - e.g. Cardio' %> - 
      <%= f.label "Date", class: 'sr-only' %>
      <%= f.date_select :workout_date %>
      <%= f.select(:workout_time, ["","morning","afternoon","evening","night"]) %>

      <%= f.radio_button :completed, :true %>
      <%= f.label :completed_true, "Completed" %>
      <%= f.radio_button :completed, :false %>
      <%= f.label :completed_false, "Scheduled" %>
      <br>
      <br>

      <%= render 'layouts/workout_form2', f: f %>

      <%= f.submit "Add Workout"%>

    <% end %>

app/views/workouts/schedule_workouts.html.erb
<h3>Create Full Schedule</h3>
<br>

		<% @templates.each do |template| %>
		<div class="template-container">
			<%= div_for template do %>
				<%= check_box_tag 'template', template.id, nil, data: {template_name: template.name} %>
				<%= label template.id, template.name %>
				<%= select_tag :how_scheduled, options_for_select(["Schedule by number of days",
																   "Select by days of week"]), 
																   class: 'how_scheduled' %>
				<br>
				<div class="num_of_days">
					Workout every 
					<%= select_tag :every_num_of_days, options_for_select(["1","2","3","4","5","6","7"], "3") %>
					 days.
				</div>
				<div class="days_of_week">
					Workout on 
					<%= check_box_tag :day_of_week, 1, nil, class: 'day_of_week' %>
					<%= label_tag 'Monday' %>
					<%= check_box_tag :day_of_week, 2, nil, class: 'day_of_week' %>
					<%= label_tag 'Tuesday' %>
					<%= check_box_tag :day_of_week, 3, nil, class: 'day_of_week' %>
					<%= label_tag 'Wednesday' %>
					<%= check_box_tag :day_of_week, 4, nil, class: 'day_of_week' %>
					<%= label_tag 'Thursday' %>
					<%= check_box_tag :day_of_week, 5, nil, class: 'day_of_week' %>
					<%= label_tag 'Friday' %>
					<%= check_box_tag :day_of_week, 6, nil, class: 'day_of_week' %>
					<%= label_tag 'Saturday' %>
					<%= check_box_tag :day_of_week, 0, nil, class: 'day_of_week' %>
					<%= label_tag 'Sunday' %>
				</div>
				<br>
				Schedule these workouts from <%= date_field_tag 'start_date', Date.today %>
				 to <%= date_field_tag 'end_date', Date.today + 14 %>
				<br>
			<% end %>
		</div>
		<% end %>
		<div class="template-container">
			<%= button_tag 'Preview', id: 'preview' %>
			<%= button_tag 'Save', id: 'save', disabled: true %>
			<span id='save_success'></span>
		</div>

		<div class='calendar-container'>
			<div id='calendar'></div>
		</div>

<%= render 'layouts/calendar_events' %>

app/views/workouts/show.html.erb
<h1><%= @this_workout.name %></h1>

<h3>
	<% if @this_workout.completed %>
		Completed on 
	<% else %>
		Scheduled for 
	<% end %>
	<%= @this_workout.workout_date.to_s %>
</h3>

<%= render 'layouts/show_exercises' %>

<p><%= @this_workout.notes %></p>

<%= link_to "update", edit_workout_path %><br>

<%= link_to "delete", workout_path, method: :delete %><br>