config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#home'

  resources :workout_components, :workouts, :templates

  get 'schedule_workouts' => 'workouts#schedule_workouts', as: :schedule_workouts
  post 'save_schedule' => 'workouts#save_schedule', as: :save_schedule

end

app/views/templates/edit.html.erb
<h3>Update Template</h3>
<br>
    <%= form_for(@workout) do |f| %>

      <%= f.label "Name", class: 'sr-only' %>
      <%= f.text_field :name, placeholder: 'Name - e.g. Cardio' %><br>
      <br>
      <br>

      <%= render 'layouts/workout_form2', f: f %>

      <%= f.submit "Update Workout"%>

    <% end %>

app/views/templates/index.html.erb
<h3>All Templates</h3>
<br>

<table class="table">


<% @workouts.each do |workout| %>
  <tbody class="template" id="template_<%= workout.id %>" %> 	
    <td>
      <% if workout.name.empty? %>
      	<%= link_to "Workout", template_url(workout.id) %>
      <% else %>
      	<%= link_to workout.name, template_url(workout.id) %>
      <% end %>
    </td>
    <td><%= link_to "view", template_url(workout.id) %></td>
    <td><%= link_to "update", edit_template_path(workout.id) %></td>
    <td><%= link_to "delete", workout, method: :delete, remote: true %></td>
  </tbody>
<% end %>

</table>

app/views/templates/new.html.erb
<h3>Add Workout Template</h3>

<br>
    <%= form_for(@workout) do |f| %>

      <%= f.label "Name", class: 'sr-only' %>
      <%= f.text_field :name, placeholder: 'Name - e.g. Cardio' %>
      <br>
      <br>

      <%= render 'layouts/workout_form2', f: f %>

      <%= f.submit "Save Template"%>

    <% end %>

app/views/templates/show.html.erb
<h1><%= @this_workout.name %></h1>

<%= render 'layouts/show_exercises' %>

<p><%= @this_workout.notes %></p>

<%= link_to "update", edit_template_path %><br>
<%= link_to "delete", template_path, method: :delete %><br>
<%= link_to "Record or schedule workout with this template", new_workout_url(template: @this_workout.id) %><br>