config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#home'

  resources :workout_components, :workouts, :templates

  get 'schedule_workouts' => 'workouts#schedule_workouts', as: :schedule_workouts
  post 'save_schedule' => 'workouts#save_schedule', as: :save_schedule

end

app/views/layouts/_calendar_events.html.erb
<script type='text/javascript'>
	var newWorkoutUrl = '<%= url_for new_workout_url %>';
	var newEventsArray = [];
	var eventsArray =
	    [
			<% @workouts.each do |workout| %>
		        {	
		        	<% if workout.completed == true %>
			        	<% if workout.name.empty? %>
			            	title: 'Workout',
			            <% else %>
			            	title: '<%= workout.name %>',
			            <% end %>
			            
			            url: '<%= url_for workout %>',
			            	//Adding colors for different time periods along with generic times so 
			            	//that they are ordered within each calendar day
			            <% if workout.workout_time == 'morning' %>
			            	start: '<%= workout.workout_date.to_s %>T05:00:00',
			            	color: '#00CCFF'
			            <% elsif workout.workout_time == 'evening' %>
			            	start: '<%= workout.workout_date.to_s %>T17:00:00',
			            	color: '#000099'
			            <% elsif workout.workout_time == 'night' %>
			            	start: '<%= workout.workout_date.to_s %>T22:00:00',
			            	color: '#000066'
			            <% else %>
			            	start: '<%= workout.workout_date.to_s %>T13:00:00',
			            	color: '#0000FF'
			            <% end %>
			        <% else %>
			        				        	<% if workout.name.empty? %>
			            	title: 'Workout',
			            <% else %>
			            	title: '<%= workout.name %>',
			            <% end %>
			            
			            url: '<%= url_for workout %>',
			            	//Adding colors for different time periods along with generic times so 
			            	//that they are ordered within each calendar day
			            <% if workout.workout_time == 'morning' %>
			            	start: '<%= workout.workout_date.to_s %>T05:00:00',
			            	color: '#FFFF66',
			            	textColor: 'black'
			            <% elsif workout.workout_time == 'evening' %>
			            	start: '<%= workout.workout_date.to_s %>T17:00:00',
			            	color: '#FFCC00',
			            	textColor: 'black'
			            <% elsif workout.workout_time == 'night' %>
			            	start: '<%= workout.workout_date.to_s %>T22:00:00',
			            	color: '#FF9900',
			            	textColor: 'black'
			            <% else %>
			            	start: '<%= workout.workout_date.to_s %>T13:00:00',
			            	color: '#FFFF00',
			            	textColor: 'black'
			            <% end %>
			        <% end %>
		        },
	        <% end %>
    	];
</script>

app/views/layouts/_component_sets_copy.json.erb
    <div class='exercise-fields'>
      <select id="workout_component_sets_attributes_<%= count %>_workout_component_id" name="workout[component_sets_attributes][<%= count %>][workout_component_id]"><option selected="selected" value="2">Bicep Curl</option>
<option value="3">Chest Press</option>
<option value="5">Shoulder Press</option>
<option value="6">Lat Pulldown</option></select>
      <input class="number-entry" id="workout_component_sets_attributes_0_kg" name="workout[component_sets_attributes][0][kg]" type="number" />kg 
      <input class="number-entry" id="workout_component_sets_attributes_0_reps" name="workout[component_sets_attributes][0][reps]" type="number" />reps 
      <input class="number-entry" id="workout_component_sets_attributes_0_num_of_sets" name="workout[component_sets_attributes][0][num_of_sets]" type="number" />sets 
       - Rest: <input class="number-entry" id="workout_component_sets_attributes_0_rest" name="workout[component_sets_attributes][0][rest]" type="number" />s
      <input class="destroy" id="workout_component_sets_attributes_0__destroy" name="workout[component_sets_attributes][0][_destroy]" type="hidden" value="false" />
      <a class="removeExercise" href="#"><img alt="Remove" src="/assets/remove.png" /></a>
    </div>

app/views/layouts/_footer.html.erb
</div>

app/views/layouts/_header.html.erb
<div class="container">
  <nav class="navbar navbar-default" role="navigation">
  	<div class="container-fluid">
		<%= link_to "Training Tracker", root_path, class: 'navbar-brand' %>
		<p class="navbar-text"><%= notice %></p>
		<p class="navbar-text"><%= alert %></p>
		<ul class="nav navbar-nav navbar-right">
		  <% if user_signed_in? %>
		  	<li><p class="navbar-text"><%= current_user.email %></p></li>
		    <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
		  <% else %>
		    <li><%= link_to 'Sign Up', new_user_registration_path %></li>
		    <li><%= link_to 'Log In', new_user_session_path %></li>	
		  <% end %>
		</ul>
	</div>
  </nav>

app/views/layouts/_new_sets.html.erb
  
  <%= f.fields_for :component_sets do |h| %>
    <tbody class='exercise-fields sets'>
      <tr>
        <%= h.hidden_field :order %>
        <td><%= h.select(:workout_component_id, @set_component_array) %></td>
        <td><%= h.number_field :kg, class: 'number-entry'  %> kg</td>
        <td><%= h.number_field :reps, class: 'number-entry' %> reps .   
        <%= h.number_field :num_of_sets, class: 'number-entry' %> sets </td>
        <td>Rest: <%= h.number_field :rest, class: 'number-entry' %>s</td>
        <td><%= h.hidden_field '_destroy', value: false, class: 'destroy' %>
        <%= link_to image_tag('remove.png'), '#', class: "removeExercise" %></td>
      </tr>
    </tbody>
    <script type='text/javascript'>componentsCount['sets']++;</script>
  <% end %>

app/views/layouts/_new_times.html.erb
  <%= f.fields_for :component_times do |h| %>
    <tbody class='exercise-fields times'>
      <tr>
        <%= h.hidden_field :order %>
        <td><%= h.select(:workout_component_id, @time_component_array) %></td>
        <td><%= h.number_field :meters, class: 'number-entry' %> meters </td>
        <td><span class="cardio-time">
          <input type="number" class="number-entry-time hours" min="0" max="60" placeholder="hh">
          <input type="number" class="number-entry-time mins" min="0" max="60" placeholder="mm">
          <input type="number" class="number-entry-time secs" min="0" max="72" placeholder="ss">
          <%= h.hidden_field :seconds, class: "actual-seconds" %>
        </span></td>
        <td>Rest: <%= h.number_field :rest, class: 'number-entry' %>s</td>
        <td><%= h.hidden_field '_destroy', value: false, class: 'destroy' %>
        <%= link_to image_tag('remove.png'), '#', class: "removeExercise" %></td>
      </tr>
    </tbody>
    <script type='text/javascript'>componentsCount['times']++;</script>
  <% end %>

app/views/layouts/_right_panel.html.erb
<div class="col-md-4">
	<div id='right-panel'>
	  <% if user_signed_in? %>
		<% if current_page?('/') %>
			<h3>How to use this site</h3>
			<p>Click on a date on the calendar to record or schedule an individual workout.</p>
			<p>You can also use the links below to create templates of your usual workouts and 
				generate a schedule.</p>
		<% end %>
		<h3>Workout Templates</h3>
		<% @templates.each do |template| %>
		  <% if template.name.empty? %>
		    Template Workout
		  <% else %>
		    <%= template.name %>
		  <% end %>
		   - <%= link_to "View", template_url(template.id) %>
		   - <%= link_to "Add Workout", new_workout_url(template: template.id, date: params[:date]) %><br>
		<% end %>
		<%= link_to "Create New Workout Template", new_template_url %>
		<h3><%= link_to "Create Full Schedule", schedule_workouts_url %></h3>
		<p>Schedule multiple workouts at once based on your templates.</p>
		<% if current_page?('/') %>
		<h3>Recent Scheduled Workouts</h3>
			<% if @recent_scheduled.length == 0 %>
				<p>There are no scheduled workouts due to be marked as complete.</p>
			<% else %>
				<p>Have you completed the following workouts?</p>
				<% @recent_scheduled.each do |workout| %>
					<%= div_for workout do %>
						<%= workout.workout_date %> - <%= workout.name %>
						- <%= link_to "View", workout_url(workout.id) %>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
		<h3><%= link_to "View All Workouts", workouts_url %></h3>
		<p>View all of your completed and scheduled workouts in a list.</p>
	  <% else %>
	  	<h3>Welcome</h3>
	  	<p>This site allows you to record and schedule your exercise.</p>
	  	<p>You will be able to create exercise 'templates', e.g. one for a cardio workout and 
	  	  another for a strength workout. You can then easily schedule these workouts one-by-one 
	  	  or in bulk.</p>
	  	<p>To begin using this site, <%= link_to 'sign up', new_user_registration_path %> or 
	  		<%= link_to 'log in', new_user_session_path %>.</p>
	  	<br>
	  	<p>The is an early version of this site. New features will be added over time.</p>
	  	<p>For anyone referred here regarding the code of the site, this can be viewed on 
	  	<a href='http://github.com/brendancox/training_tracker'>Github</a>.</p>
	  <% end %>
	</div>
</div>

app/views/layouts/_show_exercises.html.erb

<table class='table'>

  <% unless @this_workout.component_sets.empty? %>
    <tr>
      <th>Exercise</th>
      <th>Equipment</th>
      <th>Weight (kg)</th>
      <th>Reps</th>
      <th>Sets</th>
      <th>Rest</th>
    </tr>
  <% end %>

  <% @this_workout.component_sets.each do |component_set| %>
    <tr>
      <td><%= component_set.workout_component.name %></td>
      <td><%= component_set.workout_component.equipment %></td>
      <td><%= component_set.kg %></td>
      <td><%= component_set.reps %></td>
      <td><%= component_set.num_of_sets %></td>
      <td><%= component_set.rest %></td>
    </tr>
  <% end %>

  <% unless @this_workout.component_times.empty? %>
    <tr>
      <th>Exercise</th>
      <th>Equipment</th>
      <th>Distance (m)</th>
      <th>Time (s)</th>
      <th>--</th>
      <th>Rest</th>
    </tr>
  <% end %>

  <% @this_workout.component_times.each do |component_time| %>
    <tr>
      <td><%= component_time.workout_component.name %></td>
      <td><%= component_time.workout_component.equipment %></td>
      <td><%= component_time.meters %></td>
      <td><%= component_time.seconds %></td>
    </tr>
  <% end %>

</table>

app/views/layouts/_workout_form2.html.erb

  <script type='text/javascript'>var componentsCount = {sets: 0, times: 0};</script>

  <table class='table'>

  <%= render 'layouts/new_times', f: f %>

  <%= render 'layouts/new_sets', f: f %>

  </table>

  <%= link_to 'Add Strength/Toning Exercise', '#', class: 'addRepsExercise' %> - 
  <%= link_to 'Add Cardio Exercise', '#', class: 'addCardioExercise' %><br>
  <%= f.label "Notes", class: 'sr-only' %>
  <%= f.text_area :notes, placeholder: 'Notes' %>
  <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrainingTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="row">
	<div class="col-md-8">
		<%= yield %>
	</div>
	<%= render 'layouts/right_panel' %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>